const SIGHASH_ALL = 0x01;
const SIGHASH_NONE = 0x02;
const SIGHASH_SINGLE = 0x03;
const SIGHASH_ANYONECANPAY = 0x80;
const SIGHASH_ALL_ANYONECANPAY = SIGHASH_ALL | SIGHASH_ANYONECANPAY;
const SIGHASH_NONE_ANYONECANPAY = SIGHASH_NONE | SIGHASH_ANYONECANPAY;
const SIGHASH_SINGLE_ANYONECANPAY = SIGHASH_SINGLE | SIGHASH_ANYONECANPAY;

const DEFAULT_SEQUENCE = 0xffffffff;

const ADVANCED_TRANSACTION_MARKER = 0x00;
const ADVANCED_TRANSACTION_FLAG = 0x01;

export {
  SIGHASH_ALL,
  SIGHASH_NONE,
  SIGHASH_SINGLE,
  SIGHASH_ANYONECANPAY,
  SIGHASH_ALL_ANYONECANPAY,
  SIGHASH_NONE_ANYONECANPAY,
  SIGHASH_SINGLE_ANYONECANPAY,

  DEFAULT_SEQUENCE,

  ADVANCED_TRANSACTION_FLAG,
  ADVANCED_TRANSACTION_MARKER,
};